### ISSUE TITLE
Allow Integration operations in batch

### ISSUE THREAD

**Issue by monsieurBelbo** [nominal-systems/dmi-api-admin-ui#53]
Allow to start/stop/restart/test Integrations in batch

**Comment by Ceibo** [comment]
When doing this:
1. Click on the `Select all` checkbox when there are more than 10 integrations (1 page).
2. After selecting the first 10 integrations, go to the second page.
3. Go back to the first page.

Then it shows like this:
<img width="1058" alt="Screenshot 2024-10-09 at 10 10 38 AM" src="https://github.com/user-attachments/assets/18bb69be-6974-4a57-aed6-5e028544bef4">

It behaves oposite to the checkbox selection.

I'm thinking that it could keep the previously selected integrations and be able to select more as we go through pages, so the user can do batch operations with more than 10 integrations at a time.

**Comment by Ceibo** [comment]
Instead of showing this when trying to perform batch operations without any integrations selected, I think it would be better to dislpay a message indicating that one or more integrations must be selected.
<img width="600" alt="Screenshot 2024-10-09 at 10 30 32 AM" src="https://github.com/user-attachments/assets/c750579e-8954-476b-bf83-fc01c227e94d">

**Comment by monsieurBelbo** [comment]
- Allowing selection during pagination
- Showing number of rows selected
- Disabled dropdown if no rows are selected

**Comment by Ceibo** [comment]
Tested and working fine.
